import AnimeInfo from "@/components/AnimeInfo";
import { FC } from "react";

export const metadata = {
  title: "AniBrary | Anime Info",
  description: "Generated by create next app",
};

interface AnimeInfoPageProps {
  params: {
    animeId: any;
  };
}

const AnimeInfoPage: FC<AnimeInfoPageProps> = ({ params }) => {
  return (
    <main>
      <div className="bg-[#161A1D] h-[160px] md:h-[230px] w-full bg-[url('/images/animeinfo-wall.svg')] bg-cover bg-center"></div>
      <section className="w-full bg-[#161A1D]">
        <AnimeInfo animeInfoId={params.animeId} />
      </section>
    </main>
  );
};

export default AnimeInfoPage;
