"use client";
import Topbar from "@/components/Topbar";
import "./globals.css";
import { Montserrat } from "next/font/google";
import { QueryClient, QueryClientProvider } from "react-query";

const queryClient = new QueryClient();

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "AriBrary",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
        <body className={montserrat.className}>
          <Topbar />
          {children}
        </body>
      </QueryClientProvider>
    </html>
  );
}
